### ISSUE TITLE
I could not run the example in the readme

### ISSUE THREAD

**Issue by inconnu11** [x4nth055/emotion-recognition-using-speech#37]
Hi, I git clone the repo and install the dependency. Then I new a pyhton script which is written as the readme does. But it did not print anything and no error messages. How could this be fixed?

**Comment by x4nth055** [comment]
Hey there,

I have fixed some issues today, please `git pull` and let me know if any issues raise again.

Thanks,

**Comment by inconnu11** [comment]
Hi, I pull the new repo. And it still does not work. I copied the example 2 code and save it as eval_5emotions.py like below
![d4d6ca417d2f1443fa8cd91b65cac3c](https://user-images.githubusercontent.com/38338826/156959586-e66727d1-47c8-4186-9d82-b284ed0ebe48.png)

Then I run the command `python eval_5emotions.py ` . It did not train the model and it also did not print anything :(
![c775c2d41b20ab48398e8d774eb5da7](https://user-images.githubusercontent.com/38338826/156959781-f899b429-5e36-4866-8ef7-4075de8a4c8d.png)

**Comment by inconnu11** [comment]
thx!
